### ISSUE TITLE
a question about data mining.

### ISSUE THREAD

**Issue by Noirebao** [zzhuncle/TJCS-Courses#1]
Mr. Hua, I am sorry to disturb you at this time. However, I really have a very urgent thing. I am a student in the Department of Computer Science of Tongji University. I need to take a course called "Data Mining" this semester. I am curious why your warehouse does not include relevant materials for this course. I am really a five. It's really hard to do without your homework. Could you please submit coursework for this course?

**Comment by zzhuncle** [comment]
You cannot joke on me. You are not a five, you are a big old. So could you upload your data mining homework in this deposit?Really thanks!

**Comment by Noirebao** [comment]
> 
I am just a five, what i have done is cjb. In fact, I can do nothing without your help. I could NOT be worth of the title  of BIG OLD.

**Comment by zzhuncle** [comment]
> > 
> 
> I am just a five, what i have done is cjb. In fact, I can do nothing without your help. I could NOT be worth of the title of BIG OLD.

You're an academic star! Don't be so humble, since everyone is looking forward to your awesome work, it is so lovely for you to upload your work, really thanks! @Noirebao
